--!strict
local Players=game:GetService("Players");local ReplicatedStorage=game:GetService("ReplicatedStorage");local TweenService=game:GetService("TweenService")
local player=Players.LocalPlayer;local remotes=ReplicatedStorage:WaitForChild("LifeZeroRemotes");local action=remotes:WaitForChild("Action")::RemoteEvent
local gui=Instance.new("ScreenGui");gui.Name="LifeZeroUI";gui.ResetOnSpawn=false;gui.IgnoreGuiInset=false;gui.Parent=player:WaitForChild("PlayerGui")
local function corner(x:GuiObject,r:number?) local c=Instance.new("UICorner");c.CornerRadius=UDim.new(0,r or 10);c.Parent=x;local s=Instance.new("UIStroke");s.Color=Color3.fromRGB(255,255,255);s.Transparency=.85;s.Parent=x end
local function text(parent:Instance,value:string,size:UDim2,pos:UDim2,fontSize:number):TextLabel local l=Instance.new("TextLabel");l.Size=size;l.Position=pos;l.BackgroundTransparency=1;l.Text=value;l.TextColor3=Color3.new(1,1,1);l.TextSize=fontSize;l.Font=Enum.Font.GothamBold;l.TextXAlignment=Enum.TextXAlignment.Left;l.Parent=parent;return l end
local function button(parent:Instance,value:string,size:UDim2,pos:UDim2):TextButton local b=Instance.new("TextButton");b.Size=size;b.Position=pos;b.BackgroundColor3=Color3.fromRGB(49,118,221);b.TextColor3=Color3.new(1,1,1);b.Font=Enum.Font.GothamBold;b.TextSize=14;b.Text=value;b.Parent=parent;corner(b,8);return b end
local top=Instance.new("Frame");top.Size=UDim2.new(1,-24,0,68);top.Position=UDim2.fromOffset(12,10);top.BackgroundColor3=Color3.fromRGB(19,27,42);top.BackgroundTransparency=.08;top.Parent=gui;corner(top,14)
local cash=text(top,"$0",UDim2.fromOffset(180,28),UDim2.fromOffset(18,8),22);local gems=text(top,"◆ 0",UDim2.fromOffset(120,24),UDim2.fromOffset(18,38),16);gems.TextColor3=Color3.fromRGB(104,220,255)
local career=text(top,"CAREER LV. 1",UDim2.fromOffset(180,26),UDim2.new(1,-190,0,8),18);career.TextXAlignment=Enum.TextXAlignment.Right
local worth=text(top,"NET WORTH $0",UDim2.fromOffset(220,22),UDim2.new(1,-230,0,39),14);worth.TextXAlignment=Enum.TextXAlignment.Right;worth.TextColor3=Color3.fromRGB(255,216,90)
local needs=Instance.new("Frame");needs.Size=UDim2.fromOffset(190,112);needs.Position=UDim2.new(1,-202,0,88);needs.BackgroundColor3=Color3.fromRGB(19,27,42);needs.BackgroundTransparency=.1;needs.Parent=gui;corner(needs)
local needLabels:{[string]:TextLabel}={};for i,n in ipairs({"Hunger","Energy","Hygiene","Fun"}) do needLabels[n]=text(needs,n.." 100",UDim2.new(1,-20,0,21),UDim2.fromOffset(10,5+(i-1)*25),13) end
local quest=Instance.new("Frame");quest.Size=UDim2.new(0.42,0,0,64);quest.Position=UDim2.new(.29,0,0,88);quest.BackgroundColor3=Color3.fromRGB(33,47,72);quest.Parent=gui;corner(quest)
local questText=text(quest,"CURRENT GOAL\nClean your first trash pile!",UDim2.new(1,-20,1,-12),UDim2.fromOffset(10,6),14);questText.TextWrapped=true;questText.TextXAlignment=Enum.TextXAlignment.Center
local nav=Instance.new("Frame");nav.Size=UDim2.new(1,-24,0,62);nav.Position=UDim2.new(0,12,1,-74);nav.BackgroundColor3=Color3.fromRGB(19,27,42);nav.Parent=gui;corner(nav,14)
local panel=Instance.new("Frame");panel.Size=UDim2.new(.86,0,.64,0);panel.Position=UDim2.new(.07,0,.19,0);panel.BackgroundColor3=Color3.fromRGB(24,34,52);panel.Visible=false;panel.Parent=gui;corner(panel,14)
local panelTitle=text(panel,"",UDim2.new(1,-70,0,45),UDim2.fromOffset(18,8),23);local close=button(panel,"×",UDim2.fromOffset(42,38),UDim2.new(1,-52,0,8));close.Activated:Connect(function()panel.Visible=false end)
local scroll=Instance.new("ScrollingFrame");scroll.Size=UDim2.new(1,-24,1,-65);scroll.Position=UDim2.fromOffset(12,55);scroll.BackgroundTransparency=1;scroll.BorderSizePixel=0;scroll.ScrollBarThickness=5;scroll.AutomaticCanvasSize=Enum.AutomaticSize.Y;scroll.CanvasSize=UDim2.new();scroll.Parent=panel
local layout=Instance.new("UIListLayout");layout.Padding=UDim.new(0,8);layout.Parent=scroll
local snapshot:any={};local function clear() for _,v in ipairs(scroll:GetChildren()) do if v:IsA("GuiObject") then v:Destroy() end end end
local function row(title:string,desc:string,buttons:{any}) local f=Instance.new("Frame");f.Size=UDim2.new(1,-8,0,82);f.BackgroundColor3=Color3.fromRGB(37,51,75);f.Parent=scroll;corner(f);text(f,title,UDim2.new(.52,0,0,25),UDim2.fromOffset(12,8),16);local d=text(f,desc,UDim2.new(.58,0,0,38),UDim2.fromOffset(12,36),12);d.TextWrapped=true;d.TextColor3=Color3.fromRGB(191,202,221);for i,b in ipairs(buttons) do local x=button(f,b[1],UDim2.fromOffset(92,34),UDim2.new(1,-(100*i),.5,-17));x.Activated:Connect(b[2]) end end
local function open(name:string) panel.Visible=true;panelTitle.Text=name;clear()
	if name=="MARKET" then for _,o in ipairs(snapshot.Market or {}) do row(o.Rarity.." • "..o.Name,"$"..o.Price.." | condition "..o.Condition.."% | estimate $"..o.EstimatedLow.."–$"..o.EstimatedHigh,{{"BUY",function()action:FireServer("BuyMarket",o.OfferId)end}}) end
	elseif name=="VEHICLES" then for _,v in ipairs(snapshot.Vehicles or {}) do local avg=0;for _,x in pairs(v.Condition) do avg+=x end;avg=math.floor(avg/5);row(v.Rarity.." • "..v.Name,"Value $"..v.Value.." | condition "..avg.."%",{{"REPAIR",function()action:FireServer("Repair",{Uid=v.Uid,Part="Engine"})end},{"SELL",function()action:FireServer("SellVehicle",v.Uid)end}}) end
	elseif name=="HOME" then local houses=require(ReplicatedStorage.Shared.Config).Houses;for id,h in pairs(houses) do local owned=snapshot.Properties and snapshot.Properties[id];row(h.Name,(owned and "OWNED" or "$"..h.Price).." • Career Lv. "..h.Level,owned and {} or {{"BUY",function()action:FireServer("BuyHouse",id)end}}) end
	elseif name=="QUESTS" then local q=snapshot.Quests and snapshot.Quests.Daily;row("Daily: Complete 3 jobs",q and (q.Jobs.." / 3 • Reward $500 + 5 Gems") or "0 / 3",{{"CLAIM",function()action:FireServer("ClaimQuest")end}});row("Daily Login","Server-timed 7-day reward",{{"CLAIM",function()action:FireServer("Daily")end}})
	elseif name=="PROFILE" then row(player.DisplayName,"Career Lv. "..(snapshot.CareerLevel or 1).." • Net Worth $"..(snapshot.NetWorth or 0),{});row("Lifetime","Jobs "..((snapshot.Statistics and snapshot.Statistics.JobsCompleted) or 0).." • Restored "..((snapshot.Statistics and snapshot.Statistics.CarsRestored) or 0),{})
	else row(name,"Feature catalog and progression are saved to your profile.",{}) end
end
local names={"MARKET","VEHICLES","HOME","QUESTS","PROFILE","SHOP"};for i,n in ipairs(names) do local b=button(nav,n,UDim2.new(1/#names,-8,0,42),UDim2.new((i-1)/#names,4,0,10));b.Activated:Connect(function()open(n)end) end
local notice=text(gui,"",UDim2.new(.6,0,0,90),UDim2.new(.2,0,.4,0),28);notice.BackgroundColor3=Color3.fromRGB(24,34,52);notice.BackgroundTransparency=1;notice.TextXAlignment=Enum.TextXAlignment.Center;notice.TextTransparency=1;notice.ZIndex=20;corner(notice,14)
(remotes.Notify::RemoteEvent).OnClientEvent:Connect(function(data) notice.Text=data.Text or "";notice.BackgroundTransparency=.08;notice.TextTransparency=0;notice.TextColor3=if data.Kind=="Error" then Color3.fromRGB(255,100,100) elseif data.Kind=="Big" then Color3.fromRGB(255,219,82) else Color3.new(1,1,1);notice.Size=UDim2.new(.5,0,0,75);TweenService:Create(notice,TweenInfo.new(.25,Enum.EasingStyle.Back),{Size=UDim2.new(.6,0,0,90)}):Play();task.delay(3,function()TweenService:Create(notice,TweenInfo.new(.4),{TextTransparency=1,BackgroundTransparency=1}):Play()end) end)
(remotes.Sync::RemoteEvent).OnClientEvent:Connect(function(data) snapshot=data;cash.Text="$"..tostring(data.Cash);gems.Text="◆ "..tostring(data.Gems);career.Text="CAREER LV. "..data.CareerLevel;worth.Text="NET WORTH $"..data.NetWorth;for n,l in pairs(needLabels) do l.Text=n.."  "..math.floor(data.Needs[n]) end;local q=data.Quests.Daily;questText.Text=if data.TutorialStep==1 then "CURRENT GOAL\nClean your first trash pile in Town Square!" else "DAILY QUEST\nComplete jobs: "..q.Jobs.." / 3" end)
action:FireServer("Snapshot")
